name = "CTViz"
version = "0.1.0"
defaultTargets = ["ctviz"]

[[require]]
name = "scilean"
git = "https://github.com/lecopivo/SciLean"

[[lean_lib]]
name = "CTViz"

[[lean_exe]]
name = "ctviz"
root = "Main"

